[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" }
serde = "1.0"
net_decode = { path = "../clipper/crates/net_decode" }

expect-test = "1.4.1"
tracing-test = "0.2.4"
